spring:
  datasource:
    url: jdbc:mysql://localhost:3306/secure_capita?createDatabaseIfNotExist=true
    username: root
    password: SpiralStaircase
  jpa:
    databasePlatform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddlAuto: update
    properties:
      hibernate:
        globally_quoted_identifier: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  sql:
    init:
      mode: never
      continueOnError: false

